### ISSUE TITLE
Remove this integration from analytics.js

### ISSUE THREAD

**Issue by sperand-io** [segment-integrations/analytics.js-integration-customerio#2]
Need to sit down with @calvinfo to hammer out how to go about the swap, but we should remove this integration from analytics.js and instead send them data only via the server-side integration :) This is just redundant code under maintenance in the meanwhile :)

One caveat: we'll need to implement `page` on the server

**Comment by hankim813** [comment]
added to jira for internal triage https://segment.atlassian.net/browse/INT-162
